// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import ClaimUsernameReducer from "../claim_username_reducer";
import CompleteBlockReducer from "../complete_block_reducer";
import CreateBlockReducer from "../create_block_reducer";
import CreateBookReducer from "../create_book_reducer";
import CreateChapterReducer from "../create_chapter_reducer";
import DeleteBlockReducer from "../delete_block_reducer";
import PublishBookReducer from "../publish_book_reducer";
import ReorderChaptersReducer from "../reorder_chapters_reducer";
import SetChapterDepsReducer from "../set_chapter_deps_reducer";
import SetQuizReducer from "../set_quiz_reducer";
import UpdateBlockReducer from "../update_block_reducer";
import UpdateBookReducer from "../update_book_reducer";
import UpdateChapterReducer from "../update_chapter_reducer";

export type ClaimUsernameParams = __Infer<typeof ClaimUsernameReducer>;
export type CompleteBlockParams = __Infer<typeof CompleteBlockReducer>;
export type CreateBlockParams = __Infer<typeof CreateBlockReducer>;
export type CreateBookParams = __Infer<typeof CreateBookReducer>;
export type CreateChapterParams = __Infer<typeof CreateChapterReducer>;
export type DeleteBlockParams = __Infer<typeof DeleteBlockReducer>;
export type PublishBookParams = __Infer<typeof PublishBookReducer>;
export type ReorderChaptersParams = __Infer<typeof ReorderChaptersReducer>;
export type SetChapterDepsParams = __Infer<typeof SetChapterDepsReducer>;
export type SetQuizParams = __Infer<typeof SetQuizReducer>;
export type UpdateBlockParams = __Infer<typeof UpdateBlockReducer>;
export type UpdateBookParams = __Infer<typeof UpdateBookReducer>;
export type UpdateChapterParams = __Infer<typeof UpdateChapterReducer>;

