// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  chapterId: __t.u64().primaryKey().name("chapter_id"),
  bookId: __t.u64().name("book_id"),
  title: __t.string(),
  description: __t.string(),
  position: __t.u32(),
  isOptional: __t.bool().name("is_optional"),
  isPinned: __t.bool().name("is_pinned"),
  locale: __t.option(__t.string()),
  createdAt: __t.timestamp().name("created_at"),
  updatedAt: __t.timestamp().name("updated_at"),
});
