// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  BlockType,
} from "./types";


export default __t.row({
  blockId: __t.u64().primaryKey().name("block_id"),
  chapterId: __t.u64().name("chapter_id"),
  title: __t.string(),
  get blockType() {
    return BlockType.name("block_type");
  },
  bodyHtml: __t.string().name("body_html"),
  url: __t.option(__t.string()),
  position: __t.u32(),
  isOptional: __t.bool().name("is_optional"),
  locale: __t.option(__t.string()),
  createdAt: __t.timestamp().name("created_at"),
  updatedAt: __t.timestamp().name("updated_at"),
});
