// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  questionId: __t.u64().primaryKey().name("question_id"),
  blockId: __t.u64().name("block_id"),
  promptHtml: __t.string().name("prompt_html"),
  position: __t.u32(),
  isMultiAnswer: __t.bool().name("is_multi_answer"),
});
