// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

// The tagged union or sum type for the algebraic type `BlockType`.
export const BlockType = __t.enum("BlockType", {
  Reading: __t.unit(),
  ResourceLink: __t.unit(),
  Quiz: __t.unit(),
});
export type BlockType = __Infer<typeof BlockType>;

export const Book = __t.object("Book", {
  bookId: __t.u64(),
  owner: __t.identity(),
  title: __t.string(),
  description: __t.string(),
  get status() {
    return BookStatus;
  },
  locale: __t.option(__t.string()),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type Book = __Infer<typeof Book>;

// The tagged union or sum type for the algebraic type `BookStatus`.
export const BookStatus = __t.enum("BookStatus", {
  Draft: __t.unit(),
  Published: __t.unit(),
});
export type BookStatus = __Infer<typeof BookStatus>;

export const Chapter = __t.object("Chapter", {
  chapterId: __t.u64(),
  bookId: __t.u64(),
  title: __t.string(),
  description: __t.string(),
  position: __t.u32(),
  isOptional: __t.bool(),
  isPinned: __t.bool(),
  locale: __t.option(__t.string()),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type Chapter = __Infer<typeof Chapter>;

export const ChapterDep = __t.object("ChapterDep", {
  depId: __t.u64(),
  chapterId: __t.u64(),
  dependsOnChapterId: __t.u64(),
});
export type ChapterDep = __Infer<typeof ChapterDep>;

export const KnowledgeBlock = __t.object("KnowledgeBlock", {
  blockId: __t.u64(),
  chapterId: __t.u64(),
  title: __t.string(),
  get blockType() {
    return BlockType;
  },
  bodyHtml: __t.string(),
  url: __t.option(__t.string()),
  position: __t.u32(),
  isOptional: __t.bool(),
  locale: __t.option(__t.string()),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type KnowledgeBlock = __Infer<typeof KnowledgeBlock>;

export const QuizAnswerInput = __t.object("QuizAnswerInput", {
  questionId: __t.u64(),
  selectedOptionIds: __t.array(__t.u64()),
});
export type QuizAnswerInput = __Infer<typeof QuizAnswerInput>;

export const QuizAnswerKey = __t.object("QuizAnswerKey", {
  optionId: __t.u64(),
  questionId: __t.u64(),
});
export type QuizAnswerKey = __Infer<typeof QuizAnswerKey>;

export const QuizAttempt = __t.object("QuizAttempt", {
  attemptId: __t.u64(),
  identity: __t.identity(),
  blockId: __t.u64(),
  scorePercent: __t.u32(),
  passed: __t.bool(),
  submittedAt: __t.timestamp(),
});
export type QuizAttempt = __Infer<typeof QuizAttempt>;

export const QuizAttemptResult = __t.object("QuizAttemptResult", {
  resultId: __t.u64(),
  attemptId: __t.u64(),
  questionId: __t.u64(),
  isCorrect: __t.bool(),
});
export type QuizAttemptResult = __Infer<typeof QuizAttemptResult>;

export const QuizConfig = __t.object("QuizConfig", {
  blockId: __t.u64(),
  passThreshold: __t.u32(),
});
export type QuizConfig = __Infer<typeof QuizConfig>;

export const QuizOption = __t.object("QuizOption", {
  optionId: __t.u64(),
  questionId: __t.u64(),
  textHtml: __t.string(),
  position: __t.u32(),
});
export type QuizOption = __Infer<typeof QuizOption>;

export const QuizOptionInput = __t.object("QuizOptionInput", {
  textHtml: __t.string(),
  isCorrect: __t.bool(),
});
export type QuizOptionInput = __Infer<typeof QuizOptionInput>;

export const QuizQuestion = __t.object("QuizQuestion", {
  questionId: __t.u64(),
  blockId: __t.u64(),
  promptHtml: __t.string(),
  position: __t.u32(),
  isMultiAnswer: __t.bool(),
});
export type QuizQuestion = __Infer<typeof QuizQuestion>;

export const QuizQuestionInput = __t.object("QuizQuestionInput", {
  promptHtml: __t.string(),
  get options() {
    return __t.array(QuizOptionInput);
  },
});
export type QuizQuestionInput = __Infer<typeof QuizQuestionInput>;

export const ReaderProgress = __t.object("ReaderProgress", {
  progressId: __t.u64(),
  identity: __t.identity(),
  blockId: __t.u64(),
  completedAt: __t.timestamp(),
});
export type ReaderProgress = __Infer<typeof ReaderProgress>;

export const User = __t.object("User", {
  identity: __t.identity(),
  username: __t.string(),
  displayName: __t.string(),
  createdAt: __t.timestamp(),
});
export type User = __Infer<typeof User>;

